name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g npm@latest

      - name: Build project
        run: |
          echo "VITE_BASE_URL=/RSAnalytics-portfolio/" > .env.production
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          clean-exclude: |
            .nojekyll
            404.html
            CNAME
            .gitignore
      
      - name: Add nojekyll
        run: |
          touch dist/.nojekyll
          echo "RSAnalytics-portfolio" > dist/CNAME
